//  NSString+ImageDataList.m
//  PalmRecognizer
//
//  Created by Водолазкий В.В. on 28 May Tue 10:21:8
//  Copyright © 2019 Geomatix Laboratory S.R.O. All rights reserved.
//
//  DO NOT EDIT! This file is autogenerated by GenerateImageSet.pl script
//

#import "ImageList+ImageDataList.h"

@implementation ImageList  (ImageDataList)

- (NSArray *) imageSet
{
		NSArray *imSet = @[
		// List of template images
			@[@"5_1558129955.jpg",@""],
			@[@"5_1558194232.jpg",@""],
			@[@"5_1558193733.jpg",@""],
		// Test files for set 5_1558129955
			@[@"5_1558130295.jpg",@"5_1558129955"],
			@[@"5_1558130079.jpg",@"5_1558129955"],
			@[@"5_1558193642.jpg",@"5_1558129955"],
			@[@"5_1558130014.jpg",@"5_1558129955"],
			@[@"5_1558193584.jpg",@"5_1558129955"],
		// Test files for set 5_1558194232
			@[@"5_1558194308.jpg",@"5_1558194232"],
		// Test files for set 5_1558193733
			@[@"5_1558193865.jpg",@"5_1558193733"],
			@[@"5_1558194105.jpg",@"5_1558193733"],
			@[@"5_1558194039.jpg",@"5_1558193733"],
			@[@"5_1558193803.jpg",@"5_1558193733"],
			@[@"5_1558194163.jpg",@"5_1558193733"],
	];
	return imSet;
}

@end
