//  NSString+ImageDataList.m
//  PalmRecognizer
//
//  Created by Водолазкий В.В. on 24 May Fri 10:41:33
//  Copyright © 2019 Geomatix Laboratory S.R.O. All rights reserved.
//
//  DO NOT EDIT! This file is autogenerated by GenerateImageSet.pl script
//

#import "ImageList+ImageDataList.h"

@implementation NSString (ImageDataList)

- (NSArray *) imageSet
{
		NSArray *imSet = @[
		// List of template images
			@[@"5_1558129955.jpg",@""],
			@[@"5_1558194232.jpg",@""],
			@[@"5_1558193733.jpg",@""],


	];
	return imSet;
}


@end
